config/routes.rb
Rails.application.routes.draw do
  

  
  root :to => "welcome#index"

  resources :posts
  resources :projects
  resources :contacts

  resources :users

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  namespace :admin do
    root :to => "base#index"
    resources :users

  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :name, presence: true
	validates :news, presence: true

	belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, :email, :issue, :sector, :image, :phone, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_filter :authorize_admin!

	def index
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
  	@users = User.order(:email)
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		flash[:notice] = "El nuevo usuario se ha creado."
  		redirect_to admin_users_path
  	else
  		flash.now[:alert] = "El usuario no ha sido creado."
  		render :action => "new"
  	end
  end

  def show
   
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    if @user.update(user_params)
      flash[:notice] = "El Usuario se ha modificado."
      redirect_to admin_users_path
    else
      flash[:alert] = "El Usuario no ha sido modificado."
      render action: "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "No te puedes eliminar a ti mismo."

    else 
      @user.destroy
      flash[:notice] = "El Usuario ha sido eliminado."
     
    end 
     redirect_to admin_users_path

  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :posts, :projects)
  	end

    def set_user
       @user = User.find(params[:id])
    end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
    def authorize_admin!
        require_login!
        unless current_user.admin?
            flash[:alert] = "Debes loggearte como administrador para hacer eso."
            redirect_to root_path
      end
    end
  def require_login!
  		if current_user.nil?
  			flash[:error] = "Necesitas loggearte para continuar."
  			redirect_to login_url
  		end
  end
  helper_method :require_login!

  def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def checkPosts
      if current_user.posts == false 
        flash[:error] = "No fuiste autorizado para realizar esta acción"
        redirect_to root_url
      end
  end
  helper_method :checkPosts

  def checkProjects
      if current_user.projects == false 
        flash[:error] = "No fuiste autorizado para realizar esta acción"
        redirect_to root_url
      end
  end
  helper_method :checkProjects
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :require_login!, except: [:index, :show]
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_login!, except: [:index, :show]
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :checkPosts, only: [:new, :create, :edit, :update, :destroy]
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			flash[:notice] = "¡Se ha creado el post! ¡Que buena noticia!"
			redirect_to @post
		else 
			flash[:alert] = "¡Ups, no se creo el post!"
			render :action => "new"
		end

	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "El post se ha modificado."
			redirect_to @post
		else 
			flash[:alert] = "¡Ups, no se modifico el post!"
			render :action => "edit"
		end
	end

	def show
	end

	def destroy 
		
		@post.destroy

		flash[:notice] = "El post se ha eliminado. ¡Ten un buen día!"
		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:name, :image, :news, :source, :shortlink)
		end

		def set_post
			@post = Post.find(params[:id])

			rescue  ActiveRecord::RecordNotFound
			flash[:alert] = "Este no es el sitio que estabas buscando, joven padawan."
			redirect_to posts_path
			
		end

		
  	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_login!, except: [:index, :show]
	before_action :set_project, only: [:show, :edit, :update, :destroy]
	before_action :checkProjects, only: [:new, :create, :edit, :update, :destroy]
	def index
		@projects = Project.all
	end

	def show
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.user = current_user
		
		if @project.save
			flash[:notice] = "Se ha creado el proyecto"
			redirect_to @project
		else 
			flash[:alert] = "No se creo el proyecto"
			render :action => "new"
		end

	end

	def edit
	end

	def update
		if @project.update(project_params)
			flash[:notice] = "El proyecto se ha modificado."
			redirect_to @project
		else 
			flash[:alert] = "No se modifico el proyecto"
			render :action => "edit"
		end
	end


	def destroy 
		
		@project.destroy

		flash[:notice] = "El proyecto se ha eliminado."
		redirect_to projects_path
	end

	private
		def project_params
			params.require(:project).permit(:name, :email, :issue, :sector, :image, :phone, :album)
		end

		def set_project
			@project = Project.find(params[:id])

			rescue  ActiveRecord::RecordNotFound
			flash[:alert] = "Este no es el sitio que estabas buscando."
			redirect_to projects_path
			
		end

		
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.where(:email => params[:login][:email]).first

		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id
			flash[:notice] = "¡Hola, otra vez! ¡Que gusto verte!"
			redirect_to root_url
		else
			flash[:error] = "Email o Password Incorrectos, trata nuevamente"
			render :new
		end
	end

	def destroy
    	session[:user_id] = nil
    	flash[:notice] = "Nos vemos."

    	redirect_to root_url
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :require_login!, except: [:index, :show]
	def index
		
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def admins_only (&block)
		block.call if current_user.try(:admin?)
	end

	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="userList">

	<div class="container">
	<h1> Usuarios Registrados </h1>
	<h3> Clic sobre el usuario para editar </h3>
	<div id='users'>
		<% @users.each do | user | %>
			<div><%= link_to user.name, [:admin, user] %></div>
		<% end %>
	</div>
	<div class="button"><%= link_to "Nuevo Usuario", new_admin_user_path %></div>
	</div>
</div>

app/views/admin/users/show.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<div class="showUser">
	<div class="container">
	<h1><%= @user.name %></h1>
		<p><%= @user.email %></p>

		<div><%= link_to "Editar Usuario", edit_admin_user_path(@user)%></div>
		<div><%= link_to "Eliminar Usuario", admin_user_path(@user), method: :delete,
		  data: { confirm: "¿Seguro de que quieres eliminar a este usuario?"} %></div>
	</div>
	<div class="goBack">
		<div class="icon"><%= image_tag "backIcon.png" %></div>
		<div class="text"><%= link_to "REGRESAR", admin_users_path %></div>
	</div>
 </div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat Social</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta charset="UTF-8">
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <div style="display:none;">{ data: no_turbolinks = true}</div>

</head>
<body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62708614-5', 'auto');
  ga('send', 'pageview');

</script>

<ul id="mmenu">
    <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Proyectos', projects_path %></li>
      <li><%= link_to 'Blog', posts_path %></li>
      <li><%= link_to 'Contacto', contacts_path %></li>
      <li>
        <nav class="loginMessage">
          <% if current_user %>

          <li>
            <li> <%= link_to "Log out", logout_path, method: :delete %></li>
          <% else %>
            
            <li><%= link_to "Log In", login_path %></li>
          </li>
          <% end %>
        </nav>
      </li>
      <li>
        <% admins_only do %>
          <%= link_to "Admin", admin_root_path %>
        <% end %>
      </li>
</ul>

<header class="header">
  <nav>
    <div class="logo">
      <%= image_tag "logo.svg" %>
    </div>  
    <div class="menu">
      <div><%= link_to 'Inicio', root_path %></div>
      <div><%= link_to 'Proyectos', projects_path %></div>
      <div><%= link_to 'Blog', posts_path %></div>
      <div><%= link_to 'Contacto', contacts_path %></div>
      <div>
        <nav class="loginMessage">
          <% if current_user %>

          <div>
            <div> <%= link_to "Log out", logout_path, method: :delete %></div>
          <% else %>
            
            <div><%= link_to "Log In", login_path %></div>
          </div>
          <% end %>
        </nav>
      </div>
      <div>
        <% admins_only do %>
          <%= link_to "Admin", admin_root_path %>
        <% end %>
      </div>
    </div>
  </nav>
</header>
<div class="spacer"></div>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>
	
<script type="text/javascript">
$(document).ready(function(){
  $('#mmenu').slicknav();
});
</script>
<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="editNews">
	<div class="container">
		<h2> Editar Post </h2>

		<%= render 'form' %>
	</div>
</div>

<div class="goBack">
	<div class="icon"><%= image_tag "backIcon.png" %></div>
	<div class="text"><%= link_to "REGRESAR", post_path(@post) %></div>
</div>

<div class="footer fixed">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>

app/views/posts/index.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>

<div class="newsHeader">
	<div class="container">
		<h1>NOTICIAS</h1>
	</div>
</div>

<div class="newsIndex">
	<div class="container">
		<div class="newsSection">
			<div class="button">
				<% if current_user and current_user.posts?%>
					<%= link_to 'Crear Noticia', new_post_path %>
				<% end %>
			</div>
			<div class="news">
				<% @posts.each do |post| %>
					<div class="new">
						<h2><%= link_to post.name, post %></h2>
						<p><%= post.news %></p>
						<div class="newsButton">
							<%= link_to 'Leer más...', post %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<div class="socialmSection">
			<div class="facebook">
				<div class="fb-page" data-href="https://www.facebook.com/ChatSocialAc" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/ChatSocialAc"><a href="https://www.facebook.com/ChatSocialAc">Chat Social, A.C.</a></blockquote></div></div>
			</div>

			<div class="twitter">
				<a class="twitter-timeline" 
				href="https://twitter.com/CHATSOCIAL_AC" 
				data-widget-id="608695645487022083"
				width = "300"
				height = "300">Tweets por @CHATSOCIAL_AC.</a>
			</div>
		</div>
	</div>
</div>

<div class="footer">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
	(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.4&appId=181369881949810";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

 </script>

app/views/posts/show.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<div class="showNews">
	<div class="container">
		<h1><%= @post.name %></h1>
		<div class="leftSection">
			<div class="postImage"><%= image_tag(@post.image) %> </div>

			<div class="logo"><%= image_tag "logo.png" %></div>
		</div>
		<div class="rightSection">
			<div class="fb-share-button" data-href="https://www.facebook.com/ChatSocialAc" data-layout="button"></div>

			<div class="tweet">
				<a href="https://twitter.com/share" class="twitter-share-button" data-text="¡Esta noticia está increíble!" data-via="chatsocial_ac">Tweet</a>
			</div>
			<div class="text"><%= @post.news %></div>

			<div class="source">Más Información:<br>
			<%= link_to @post.shortlink, @post.source, :target => "_blank" %></div>

			<% if current_user and current_user.posts?%>

				<div class="button">
				<%= link_to "Eliminar Post", post_path(@post), method: :delete %>
				</div>

				<div class="button"><%= link_to "Editar Post", edit_post_path(@post) %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<div class="goBack">
	<div class="icon"><%= image_tag "backIcon.png" %></div>
	<div class="text"><%= link_to "REGRESAR", posts_path %></div>
</div>

<div class="footer">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/projects/edit.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<div class="projectEdit">
	<div class="container">
		<h2> Editar Proyecto </h2>
		<%= render 'form' %>
	</div>

	<div class="goBack">
		<div class="icon"><%= image_tag "backIcon.png" %></div>
		<div class="text"><%= link_to "REGRESAR", project_path(@project) %></div>
	</div>
</div>

<div class="footer fixed">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>

app/views/projects/index.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<div class="projectsHeader">
	<div class="container">
		<h1>NUESTROS PROYECTOS</h1>
	</div>
</div>

<div class="projectsIndex">
	<div class="container">
		<div class="desc">
			<p>
				Estos son los proyectos con los que estamos trabajando para contribuir a la sociedad actualmente.
			</p>
			<h3>¿Qué esperas para ser parte del cambio?</h3>
			<% if current_user and current_user.projects?%>
				<div class="button"><%= link_to 'Nuevo Proyecto', new_project_path %></div>
			<% end %>

			<div class="projects">
				<% @projects.each do |project| %>
					<div class="project">
						<p><%= link_to project.name, project %></p>
						<p class="shortDesc"><%= project.issue %></p>
						<div class="seeMore"><%= link_to "VER MÁS", project %></div>
					</div>
				<% end %>
			</div>
		</div>

		<div class="createProject">
			<div class="form">
			<h2>Crea tu Proyecto</h2>
			<form id="createForm" action="//formspree.io/contacto@chatsocial.mx" method="POST" >
                <input type="text" name="Nombre" placeholder="Nombre" required>
                <input type="text" name="Email" placeholder="Email" required>
                <div class="stepGrp"> 
	                <div class="steps">
	                	<h1>1</h1>
	                	<p>¿Qué problemas sociales te gustaría resolver?</p>
	                	<textarea name="Problema" rows="4" placeholder="Escribe aquí" required></textarea>
	                </div>  
	                <div class="steps">
	                	<h1>2</h1>
	                	<p>¿En qué sector o lugar has visto estos problemas?</p>
	                	<textarea name="Sector" rows="4" placeholder="Escribe aquí" required></textarea>
	                </div>  
	                <div class="steps">
	                	<h1>3</h1>
	                	<p>¿Qué acciones podrías hacer tú?</p>
	                	<textarea name="Acciones" rows="4" placeholder="Escribe aquí" required></textarea>
	                </div>   
                </div>

            	<button type="submit"><span class="singup-text">ENVIAR</span></button>
            </form>
		</div>
		</div>
	</div>
</div>

<div class="footer">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>


app/views/projects/show.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<div class="showProject">
	<div class="container">
		<h1><%= @project.name %></h1>
		<div class="leftInfo">
			<div>
				<p class="projectDesc"><%= @project.issue %></p>
				<p class="infoH">Sector:</p>
				<p class="info"><%= @project.sector %></p>

				<p class="infoH">Contacto:</p>
				<p class="info"><%= @project.phone %></p>

				<p class="info"><%= @project.email %></p>
				<br>
				<p class="infoLink"><%= link_to "Ver Álbum de Facebook", @project.album %></p>
			</div>
			<div>
				<% if current_user and current_user.projects?%>
					<button><%= link_to "Editar Proyecto", edit_project_path(@project) %></button>
					<button><%= link_to "Borrar Proyecto", project_path(@project), method: :delete %></button>
				<% end %>
			</div>
		</div>
		<div class="rightInfo">
			<div class="projectImage"><%= image_tag @project.image %></div>
			<div class="logo"><%= image_tag "logo.png" %></div>

		</div>
	</div>

	<div class="goBack">
		<div class="icon"><%= image_tag "backIcon.png" %></div>
		<div class="text"><%= link_to "REGRESAR", projects_path %></div>
	</div>
	<div class="push"></div>
</div>

<div class="footer">
	<div class="informacion">
        <a href="https://goo.gl/maps/wSPBR">
		<p>
        Luis de Molina 163, Int 11.<br>
		San Luis Potosí, SLP. México
		<br><br>
		Tel: +52 (444) 211 7794
		</p>
        </a>
	</div>
	<div class="rSociales">
		<div class="fb">
			<a href="https://www.facebook.com/ChatSocialAc"><%= image_tag "facebook.png" %></a>
		</div>
		<div class="tw">
			<a href="https://twitter.com/CHATSOCIAL_AC"><%= image_tag "twitter.png" %></a>
		</div>
		<div class="inst">
			<a href="https://plus.google.com/u/1/113826014774182886131/about"><%= image_tag "googleplus.png" %></a>
		</div>
	</div>
	<div class="nuva">
		<div><a href="http://www.nuva.rocks"><%= image_tag "nuva2015.svg" %></a></div>
	</div>
</div>


app/views/users/show.html.erb
<%= javascript_include_tag 'jquery.slicknav', 'data-turbolinks-track' => true %>
<h1> Hola,<%= @user.name %></h1>


<p><%= @user.email %></p>


<%= link_to "Editar Perfil", edit_user_path(@user) %>